//------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of the CleanArchitecture.Blazor project.
//     Licensed to the .NET Foundation under the MIT license.
//     See the LICENSE file in the project root for more information.
//
//     Author: neozhu
//     Created Date: 2025-01-06
//     Last Modified: 2025-01-06
//     Description: 
//       Defines permission constants for lookupdetail-related operations, such as 
//       viewing, creating, editing, deleting, and more. These permissions are 
//       used to manage access control within the application.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CleanArchitecture.Blazor.Infrastructure.PermissionSet;

public static partial class Permissions
{
    [DisplayName("DepartmentWiseDesignations Permissions")]
    [Description("Set permissions for DepartmentWiseDesignations operations.")]
    public static class DepartmentWiseDesignations
    {
        [Description("Allows viewing DepartmentWiseDesignations.")]
        public const string View = "Permissions.DepartmentWiseDesignations.View";
        [Description("Allows creating DepartmentWiseDesignations.")]
        public const string Create = "Permissions.DepartmentWiseDesignations.Create";
        [Description("Allows editing DepartmentWiseDesignations.")]
        public const string Edit = "Permissions.DepartmentWiseDesignations.Edit";
        [Description("Allows deleting DepartmentWiseDesignations.")]
        public const string Delete = "Permissions.DepartmentWiseDesignations.Delete";
        [Description("Allows printing DepartmentWiseDesignations.")]
        public const string Print = "Permissions.DepartmentWiseDesignations.Print";
        [Description("Allows searching DepartmentWiseDesignations.")]
        public const string Search = "Permissions.DepartmentWiseDesignations.Search";
        [Description("Allows exporting DepartmentWiseDesignations.")]
        public const string Export = "Permissions.DepartmentWiseDesignations.Export";
        [Description("Allows importing DepartmentWiseDesignations.")]
        public const string Import = "Permissions.DepartmentWiseDesignations.Import";
    }
}

